# Site settings
author: Lauren Esser
title: DataScience101 Blog
header-img: img/home-bg.png
email: lauren.pasciak@gmail.com
copyright_name: Lauren Esser
description: > # this means to ignore newlines until "baseurl:"
  From Teacher to Data Scientist
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  lauren-esser

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
